version: "3"
services:
  vioneta:
    container_name: vioneta
    image: "ghcr.io/vioneta/vionetaos:latest"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
